replicaCount: 2

image:
  repository: hertzdataacr.azurecr.io/hertzdataapi
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: stage.hertzdataapi.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  NAME: "stage"
